image: node:wheezy

before_script:
  - apt-get update -qq && apt-get -y -qq install ruby
  - gem install sass
  - npm install
  - npm install -g grunt-cli

test:
  stage: test
  script:
  - npm run test

release:
  stage: deploy
  script:
  - grunt
  artifacts:
    paths:
    - dist
    name: "dist"
  only:
  - master

pages:
  stage: deploy
  script:
  - gem install jekyll pygments.rb
  - jekyll build -s website -d public
  artifacts:
    paths:
    - public
  only:
  - master